### ISSUE TITLE
AttributeError: 'App' object has no attribute 'attributes'

### ISSUE THREAD

**Issue by MaddMaxx2016** [raspberrypilearning/the-all-seeing-pi#17]
Hello, 

New to Python and RPI in general. When I try to set the GUI to full screen: 

# Set up GUI
app = App("The All-Seeing Pi", 800, 480)
app.attributes("-fullscreen", True)
message = Text(app, "Save Your Picture, or Take a New One.")               
your_pic = Picture(app, latest_photo)
new_pic = PushButton(app, new_picture, text="Take a New Picture")
tweet_pic = PushButton(app, send_tweet, text="Save Photo")
app.display()

I get a blank/grey GUI and this error:

Traceback (most recent call last):
  File "/home/pi/allseeingpi/allseeingpi.py", line 79, in <module>
    app.attributes("-fullscreen", True)
AttributeError: 'App' object has no attribute 'attributes'

Am I missing something? 

Any help will be greatly appreciated.

**Comment by martinohanlon** [comment]
Fixed.

This was due to a change made to guizero a while back where tk properties have to be accessed via a `tk` property, so the code should have been.

```python
app.tk.attributes("-fullscreen", True)
```

**Comment by jvinterberg** [comment]
the additional "tk." is still missing in the final code on line 77
I had the pleasure of strugling with that last night.
